# Write your code below this line 👇
print("Hello " + input("What is you name?\n"))

# Notes ->                                                                                                                                 
#print - Command that Prints a string into the console.                                                                                                                                                                
#strings - written between " " to show computer its not a code                                                                                                                                                                                                                        
#In python " " and ' ' work same (work - it encloses strings) but to print something like print('what to print') [output] , we have to write print("print('what to print')") and vice versa - print('print("what to print")')                                                                                                                                                                                                 
#Like in assignment 1 (day 1 ) , we use print function 3 time to get all statements printed on a different line , but we can use \n now and use a single print statement                                                                                                                                                                                                                .                                           
# \n - prints in a new line , its a backslash (not a foreslash)                                                                                                                                                                                                                        
#Concatenating - We can combine strings so that they can be added to  the end of another string like we can do it with a plus sign - print("Hello" + "World") , it will combine two strings "hello" and "world", it will give output of HelloWorld - it is without space bcoz we doesnt include space in it , we can do so by adding space where we want in between or at end - like there can be somthing like 3 methods to do this but this method - print("Hello" + " " + "World") in this we put a string containing space which combine it also.                                                                                                                                                               
#In Python programming , spaces are very important in it, like if put a space before print , it will give error something like indentation error etc. so be careful of spaces wheather b/w strings or anywhere .                                                                      
# Debugging - removing errors from code which can include space errors , double quote or single quote error etc . solve day 1 exercise 2 to get more idea                                                                                                                              
# -> solved                                                                                                                                                                                                                                                                               
# If u run code and got a error and not have time or idea to fix it , search the error on google - 1st link would be of stack overflow , that can help us .                                                                                                                                                                                                                                                                     
# input function - Prints a string into the console, and asks the user for a string input. it is used when we need a data from user after running this code . its syntax is input("A prompt for user") , it is different than print function as after running it waits for us give back data as instead of adding a text to be printed we are adding a prompt for user to give him a hint that we want this data.( Use \n so that is ask for data in next line just to look neat)                                                                                                                                                                                                                                    
# What can we do with this data , well we can use it inside our code - means the code input("What is your name") will act as the data which user gave like example we can use it in print("Hello " + input("What is your name\n") ) - Output will be first it will ask for input so that it can print by replacing input code . after giving data like u gave - Vansh, it will print - Hello Vansh. Also Check Spaces and all other errors and things learn . Also We can combine like we did in this string + other code that later go on and become a string.                                                                                                                                                                                                                                                                                             
#len() function - Used to calculate length of string , we used this in Assignment 3 of Day 1 . Should solve that again . The code i submitted - print(len(input("What is your name"))) and the output was length of our name, we used function inside function so that we can get the desired output according to given question . IF you have query why function inside function and other , try it yourself . i think we used input func inside len and print as we want to print the length of data given by user so if we think about this so input func will become the data and len func will calculate its length then it will be printed by print func. Also take care of spaces according to output we needed.                                                                                                                                                                                                                                                                           
# And here this day 1 printing notes end, now will start day 1 variable notes.
